### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ppremk**
This PR updates the README.md to have context and aligned to the initiative of WHO

### CODE REVIEW

**Review by stoe — DISMISSED** [review]
LGTM 👍

**Comment by ppremk** [comment]
👋  @milovanovicdusan @stoe @malakumar85 
The README.md is almost complete. Need your 👀 to add some content to the following sections:
- 🤔 When do I use this?
- Contributor Profiles

Also please feel free to approve and merge to 🚢 after edits to this PR.

**Review by malakumar85 — CHANGES_REQUESTED** [review]
**Suggestions:**

### 🤔 When do I use this?
Use this repo when you are interested in getting your organization, company, open source community, or you as an individual involved with WHO open source work. Note that if you already have an existing collaboration or partnership with WHO, you can continue to use those existing communication channels.

### Contributor Profiles
As more WHO work is open sourced, the breadth of contributor profiles will grow. Currently, WHO is seeking collaboration from the following that have an existing orientation on public health:
- UN, INGOs, MNOs, Ministries of Health
- Academic Institutions
- Private Tech Companies
- Open Source Communities
- Expert Individuals (not working on behalf of the above)

**Comment by malakumar85** [comment]
Added suggestions to the two blank sections. I'm probably out of sync since I missed the last two calls; I wanted to double check on the "How do I use this?" section. Is the idea that collaborator meeting notes and the like will be hosted on this repo? Is that important for people to know now? Or can we clarify that the next few weeks will focus on capturing collaborator interest and future uses of the repo will include those four points? 

I'm trying to view this as a new user, and I don't see how to submit my interest to collaborate until line 25, and there a lot of links out of the repo that can distract me away. To follow good UX practices, I would get that Issue link up higher and tell the reader to go through the ReadMe before submitting.

**Comment by ppremk** [comment]
@malakumar85 thank you for the review. Agreed to the points raised. Changes has been done to reflect the request. I moved some sections around and left out those not relevant for now. Please let know if this is good to go 🙂

**Comment by malakumar85** [comment]
Thanks, @ppremk ! Looks good to me overall. I think @milovanovicdusan has a few minor changes, but I think this PR is okay to merge and the rest can be done through another PR.

**Comment by ppremk** [comment]
@malakumar85 noted. Going ahead to merge and 🚢 Thank you folks for the speedy reviews 🙇

**Review by malakumar85 — APPROVED** [review]
Changes look good to me, thanks @ppremk !

**Comment by milovanovicdusan** [comment]
> Thanks, @ppremk ! Looks good to me overall. I think @milovanovicdusan has a few minor changes, but I think this PR is okay to merge and the rest can be done through another PR.

@malakumar85 (copy: @ppremk and @stoe) - no need to change anything at this point. The content of the chapter: [When do I use this](https://github.com/WorldHealthOrganization/open-source-communication-channel#-when-do-i-use-this) is perfect. Thanks, Mala!

**Comment by milovanovicdusan** [comment]
@malakumar85 @ppremk @stoe - I've done some housekeeping cleanup of the headings and commited them directly to the 🚢 to have a screenshot for immediate update of Universe slideset.

**Comment by malakumar85** [comment]
> @malakumar85 @ppremk @stoe - I've done some housekeeping cleanup of the headings and commited them directly to the 🚢 to have a screenshot for immediate update of Universe slideset.

Thanks! I'll grab a new screenshot now.

**Pull request merged**
